name: TBMM Scrape & Push

on:
  workflow_dispatch:
    inputs:
      donem:
        description: 'Dönem (ör: 23)'
        required: false
        default: '23'
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run scraper
        run: |
          DONEM="${{ github.event.inputs.donem || '23' }}"
          echo "İşlenecek dönem: $DONEM"

          node meclis/donem-parser.js --donem "$DONEM" --dest "data/donem.$DONEM.json"
          node meclis/mv-parse-all.js --file "data/donem.$DONEM.json" --donem "$DONEM" --dest "data/donem-ext.$DONEM.json"
          node ktii/parse-all.js --file "data/donem-ext.$DONEM.json" --destII "data/ii.$DONEM.json" --destMV "data/donem-ext.$DONEM.json" --donem "$DONEM"
          mkdir -p "data/kt-detay-$DONEM"
          node kt-detay/download-all.js --file "data/ii.$DONEM.json" --dest "data/kt-detay-$DONEM/" --donem "$DONEM"
          node kt-detay/parse-all.js --file "data/ii.$DONEM.json" --dest "data/kt.$DONEM.json" --contentDir "data/kt-detay-$DONEM/"

      - name: POST JSON to server
        env:
          PUSH_URL: ${{ secrets.PUSH_URL }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
        run: |
          DONEM="${{ github.event.inputs.donem || '23' }}"
          FILE="data/kt.$DONEM.json"

          if [ -f "$FILE" ]; then
            echo "Dosya bulundu: $FILE. Gönderiliyor..."
            curl -X POST "$PUSH_URL" \
              -H "X-API-KEY: $PUSH_KEY" \
              --data-binary @"$FILE" \
              -H "Content-Type: application/json"
          else
            echo "Hata: Dosya bulunamadı: $FILE"
            exit 1
          fi
