name: TBMM Scrape & Push

on:
  workflow_dispatch:
    inputs:
      donem:
        description: 'Dönem (ör: 23)'
        required: false
        default: '28'
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build-and-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Debug - Download Raw Page
        id: debug_download
        run: |
          # Scraper'ın ulaşmaya çalıştığı ana URL'i curl ile indiriyoruz.
          # -L flag'i yönlendirmeleri takip eder.
          # -A ile gerçek bir tarayıcı taklidi yapıyoruz.
          curl -L -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" \
            "https://www.tbmm.gov.tr/Yasama/KanunTeklifi" \
            -o tbmm_sayfasi.html \
            --fail --show-error --verbose
          
          echo "Sayfa indirildi. Boyutu:"
          ls -l tbmm_sayfasi.html

      - name: Upload Debug Artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-output
          path: tbmm_sayfasi.html

      #----------------------------------------------------
      # SORUNU ANLAYANA KADAR BU ADIMLARI GEÇİCİ OLARAK DEVRE DIŞI BIRAKTIM
      #----------------------------------------------------
      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'

      # - name: Install dependencies
      #   run: npm install

      # - name: Create data directory
      #   run: mkdir -p data
      
      # - name: Run scraper
      #   run: |
      #     # ... (eski scraper kodları)
